name: ftl
description: Dart parser for the Project Fluent FTL file format.
version: 1.0.0-alpha.1
author: Krzysztof Sroka <kpsroka@kpsroka.dev>
repository: https://github.com/kpsroka/dart_ftl

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  petitparser: ^2.4.0

dev_dependencies:
  test: ^1.9.4
