name: ftl
description: Dart parser for the Project Fluent FTL file format.
version: 0.0.1
author: Krzysztof Sroka <kpsroka@kpsroka.dev>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  petitparser: "2.4.0"
