name: ftl
description: Dart parser for the Project Fluent FTL file format.
version: 2.0.0-alpha.1
homepage: https://github.com/kpsroka/dart_ftl
repository: https://github.com/kpsroka/dart_ftl

environment:
  sdk: ^3.3.0

dependencies:
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
